Develop
boldlink/terraform-aws-iam-group pull request #2
Opened 2022-03-07 13:30 UTC by patrickmukumbu

updated module source link

2022-03-08 13:21 UTC, JohnNMwangi requested changes

2022-03-08 13:21 UTC, JohnNMwangi commented on terraform.tf
> +provider "aws" {
remove this one

2022-03-08 13:21 UTC, patrickmukumbu commented on terraform.tf
> +provider "aws" {
Alright

2022-03-09 13:02 UTC, JohnNMwangi approved these changes

2022-03-09 14:00 UTC, merged